services:
  mc-server:
    image: mc-server
    build:
        context: .
        dockerfile: bedrock.Dockerfile
    ports:
      - "8888:19132/tcp"
      - "8888:19132/udp"
    env_file:
      - .env
    volumes:
      - mc-server-volume:/mc-server

volumes:
  mc-server-volume:
